name: Node.js CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-test-publish:

    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v2'
      with:
        ref: '${{ github.event.release.target_commitish }}'
    - name: 'Use Node.js 16'
      uses: 'actions/setup-node@v1'
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org/'
    - run: 'echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV'
    - run: 'npm version --no-git-tag-version ${{ env.RELEASE_VERSION }}'
    - run: 'npm ci'
    - run: 'npm run build'
#    - run: 'cd tests && npm ci'
#    - run: 'cd tests && npm run test'
    - run: 'npm publish --access public'
      env:
        NODE_AUTH_TOKEN: '${{ secrets.NPM_TOKEN }}'